name: Build & Push to image ECR
run-name: dot-net-build-image-${{ inputs.AWS_REGION }}-${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: "AWS region"
        required: true
        type: choice
        default: "us-east-1"
        options:
          - us-east-1
          - eu-central-1
      environment:
        description: "environment"
        required: true
        type: choice
        default: "dev"
        options:
          - dev
          - qa

      image_tag:
        description: "Docker image tag"
        required: true
        type: string

      dockerfilePath:
        description: "Dockerfile path"
        default: Dockerfile
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.region }}
          role-skip-session-tagging: true
          role-duration-seconds: 1200

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set ECR repository name and URI
        id: ecr
        run: |
          REPO_NAME="my-service-${{ inputs.environment }}"
          echo "ECR_REPO=$REPO_NAME" >> $GITHUB_ENV
          echo "ECR_URI=${{ steps.login-ecr.outputs.registry }}/$REPO_NAME" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -f ${{ inputs.dockerfilePath }} \
            -t $ECR_URI:${{ inputs.image_tag }} .

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_URI:${{ inputs.image_tag }}
